examples:
  - changed-files:
      - any-glob-to-any-file: 'examples/**'
dockerfiles:
  - changed-files:
      - any-glob-to-any-file: 'Dockerfiles/**'
docs:
  - changed-files:
      - any-glob-to-any-file: 'docs/**'
github_actions:
  - changed-files:
      - any-glob-to-any-file: '.github/**'
feature:
  - head-branch: ['^feature', 'feature']
fix:
  - head-branch: ['^fix', 'fix']
