FROM centos:centos7

RUN yum -y install git autoconf automake libtool make \
  readline-devel texinfo net-snmp-devel groff pkgconfig \
  json-c-devel pam-devel bison flex pytest c-ares-devel \
  python-devel systemd-devel python-sphinx libcap-devel \
	sudo iproute traceroute iputils bash-completion tcpdump \
	wireshark gdb wget vim libunwind libunwind-devel \
	iptables-services
