FROM tinet/centos:centos7

RUN yum -y install https://rpm.frrouting.org/repo/frr-stable-repo-1-0.el7.noarch.rpm \
 && yum -y install frr-7.3.1-01.el7.x86_64 frr-pythontools \
 && yum -y install https://download.libreswan.org/binaries/rhel/7/x86_64/libreswan-3.32-1.el7.x86_64.rpm
